create or replace TABLE BW_HA_OBJK (
	OBKNR VARCHAR(10),
	OBZAE VARCHAR(10),
	EQUNR VARCHAR(18),
	IHNUM VARCHAR(12),
	BAUTL VARCHAR(18),
	ILOAN VARCHAR(12),
	SORTF VARCHAR(20),
	BEARB VARCHAR(1),
	OBJVW VARCHAR(1),
	SERNR VARCHAR(18),
	MATNR VARCHAR(18),
	ZZDATE VARCHAR(8),
	EQSNR VARCHAR(8),
	TASER VARCHAR(5),
	SEQGEN NUMBER(38,0),
	FRMW_EXTRACTED_ON TIMESTAMP_NTZ(9),
	SNFLK_UPDATEDON TIMESTAMP_NTZ(9)
);