create or replace TABLE BW_HA_COSTCENTER_HIERBRIDGE (
	PARENT VARCHAR(60),
	CHILD VARCHAR(60),
	ZLEVEL VARCHAR(5),
	LEVEL_NUMBER NUMBER(38,0),
	TOP_FLAG NUMBER(38,0),
	HIERARCHY VARCHAR(3000),
	REGION VARCHAR(40),
	FRMW_EXTRACTED_ON TIMESTAMP_NTZ(9),
	SNFLK_UPDATEDON TIMESTAMP_NTZ(9)
);