create or replace TABLE BW_HA_VEPO (
	VEPOS VARCHAR(6),
	VENUM VARCHAR(10),
	VBELN VARCHAR(10),
	POSNR VARCHAR(6),
	MATNR VARCHAR(18),
	WERKS VARCHAR(4),
	LGORT VARCHAR(4),
	VBTYP VARCHAR(2),
	VEMNG NUMBER(38,3),
	VEMEH VARCHAR(3),
	UNVEL VARCHAR(10),
	VELIN VARCHAR(1),
	ZZDATE VARCHAR(8),
	SEQGEN NUMBER(38,0),
	FRMW_EXTRACTED_ON TIMESTAMP_NTZ(9),
	SNFLK_UPDATEDON TIMESTAMP_NTZ(9)
);