create or replace TABLE BW_HA_GRC_RISK_DATA (
	ZRULSETID VARCHAR(8),
	ZCONNECT VARCHAR(32),
	ZRISKID VARCHAR(8),
	ZRSKLVL VARCHAR(1),
	ZACTRLID VARCHAR(4),
	ZACTION VARCHAR(50),
	ZRSKTXT VARCHAR(60),
	ZACTXT VARCHAR(60),
	ZRSKLVT VARCHAR(60),
	RECORDMODE VARCHAR(1),
	FUNCTION_ID VARCHAR(40),
	FUNCTION_TEXT VARCHAR(60),
	SEQGEN NUMBER(38,0),
	FRMW_EXTRACTED_ON TIMESTAMP_NTZ(9),
	SNFLK_UPDATEDON TIMESTAMP_NTZ(9)
);