create or replace TABLE BW_HA_VBUK (
	VBELN VARCHAR(10),
	ROCANCEL VARCHAR(1),
	VBTYP VARCHAR(2),
	VBOBJ VARCHAR(1),
	REJECTN_ST VARCHAR(1),
	GBSTK VARCHAR(1),
	LFGSK VARCHAR(1),
	LFSTK VARCHAR(1),
	BESTK VARCHAR(1),
	FKSAK VARCHAR(1),
	FKSTK VARCHAR(1),
	MANEK VARCHAR(1),
	AEDAT VARCHAR(8),
	SEQGEN NUMBER(38,0),
	FRMW_EXTRACTED_ON TIMESTAMP_NTZ(9),
	SNFLK_UPDATEDON TIMESTAMP_NTZ(9)
);