create or replace TABLE BW_HA_PROFITCENTER_HIERBRIDGE (
	PARENT VARCHAR(60),
	CHILD VARCHAR(60),
	ZLEVEL VARCHAR(5),
	LEVEL_NUMBER NUMBER(38,0),
	TOP_FLAG NUMBER(38,0),
	CO_AREA VARCHAR(4),
	HIERARCHY VARCHAR(3000),
	FRMW_EXTRACTED_ON TIMESTAMP_NTZ(9),
	SNFLK_UPDATEDON TIMESTAMP_NTZ(9)
);