create or replace TABLE BW_HA_SER06 (
	OBKNR VARCHAR(100),
	VENUM VARCHAR(10),
	VEPOS VARCHAR(6),
	EXDIV VARCHAR(20),
	DATUM VARCHAR(8),
	UZEIT VARCHAR(6),
	ANZSN VARCHAR(10),
	VORGANG VARCHAR(4),
	ZZDATE VARCHAR(8),
	SEQGEN NUMBER(38,0),
	FRMW_EXTRACTED_ON TIMESTAMP_NTZ(9),
	SNFLK_UPDATEDON TIMESTAMP_NTZ(9)
);