create or replace TABLE BW_HA_CRTX (
	WERKS VARCHAR(100),
	ARBPL VARCHAR(100),
	ARBPL_TXT VARCHAR(100),
	LANGU VARCHAR(100),
	SEQGEN NUMBER(38,0),
	FRMW_EXTRACTED_ON TIMESTAMP_NTZ(9),
	SNFLK_UPDATEDON TIMESTAMP_NTZ(9)
);