create or replace TABLE ECC_HA_SKAT (
	MANDT VARCHAR(3),
	SPRAS VARCHAR(1),
	KTOPL VARCHAR(4),
	SAKNR VARCHAR(10),
	TXT20 VARCHAR(20),
	TXT50 VARCHAR(50),
	MCOD1 VARCHAR(25),
	SEQGEN NUMBER(38,0),
	FRMW_EXTRACTED_ON TIMESTAMP_NTZ(9),
	SNFLK_UPDATEDON TIMESTAMP_NTZ(9)
);