create or replace TABLE ECC_HA_ZSD_LIKP_CHANGE (
	MANDT VARCHAR(3),
	VBELN VARCHAR(10),
	WERKS VARCHAR(4),
	AEDAT VARCHAR(8),
	ZZDATE VARCHAR(8),
	ZZTIME VARCHAR(6),
	SEQGEN NUMBER(38,0),
	FRMW_EXTRACTED_ON TIMESTAMP_NTZ(9),
	SNFLK_UPDATEDON TIMESTAMP_NTZ(9)
);