create or replace TABLE ECC_HA_T024 (
	MANDT VARCHAR(3),
	EKGRP VARCHAR(3),
	EKNAM VARCHAR(18),
	EKTEL VARCHAR(12),
	LDEST VARCHAR(4),
	TELFX VARCHAR(31),
	TEL_NUMBER VARCHAR(30),
	TEL_EXTENS VARCHAR(30),
	SMTP_ADDR VARCHAR(241),
	SEQGEN NUMBER(38,0),
	FRMW_EXTRACTED_ON TIMESTAMP_NTZ(9),
	SNFLK_UPDATEDON TIMESTAMP_NTZ(9)
);