create or replace TABLE ECC_HA_TVM4T (
	MANDT VARCHAR(3),
	SPRAS VARCHAR(1),
	MVGR4 VARCHAR(3),
	BEZEI VARCHAR(40),
	SEQGEN NUMBER(38,0),
	FRMW_EXTRACTED_ON TIMESTAMP_NTZ(9),
	SNFLK_UPDATEDON TIMESTAMP_NTZ(9)
);