create or replace TABLE ECC_HA_LINK (
	MANDT VARCHAR(3),
	LGNUM VARCHAR(3),
	IVNUM VARCHAR(10),
	ISTAT VARCHAR(1),
	DSTAT VARCHAR(1),
	NVERS VARCHAR(2),
	LGTYP VARCHAR(3),
	PDATU VARCHAR(8),
	IRNUM VARCHAR(10),
	IVAKT VARCHAR(1),
	UNAME VARCHAR(12),
	QUINV VARCHAR(1),
	ZZDATE VARCHAR(8),
	ZZTIME VARCHAR(6),
	SEQGEN NUMBER(38,0),
	FRMW_EXTRACTED_ON TIMESTAMP_NTZ(9),
	SNFLK_UPDATEDON TIMESTAMP_NTZ(9)
);