create or replace TABLE ECC_HA_A005 (
	MANDT VARCHAR(3),
	KAPPL VARCHAR(2),
	KSCHL VARCHAR(4),
	VKORG VARCHAR(4),
	VTWEG VARCHAR(2),
	KUNNR VARCHAR(10),
	MATNR VARCHAR(18),
	DATBI VARCHAR(8),
	DATAB VARCHAR(8),
	KNUMH VARCHAR(10),
	SEQGEN NUMBER(38,0),
	ZZDATE VARCHAR(8),
	ZZTIME VARCHAR(6),
	FRMW_EXTRACTED_ON TIMESTAMP_NTZ(9),
	SNFLK_UPDATEDON TIMESTAMP_NTZ(9)
);