create or replace TABLE ECC_HA_TVKWZ (
	MANDT VARCHAR(3),
	VKORG VARCHAR(4),
	VTWEG VARCHAR(2),
	WERKS VARCHAR(4),
	SEQGEN NUMBER(38,0),
	FRMW_EXTRACTED_ON TIMESTAMP_NTZ(9),
	SNFLK_UPDATEDON TIMESTAMP_NTZ(9)
);