create or replace TABLE ECC_HA_RDPR (
	MANDT VARCHAR(3),
	WERKS VARCHAR(4),
	RDPRF VARCHAR(4),
	RDZAE VARCHAR(6),
	BDMNG NUMBER(38,3),
	VORMG NUMBER(38,3),
	RDMPO VARCHAR(1),
	RDRGL VARCHAR(2),
	CHKMELI VARCHAR(1),
	CHKMEKU VARCHAR(1),
	FRMW_EXTRACTED_ON TIMESTAMP_NTZ(9),
	SNFLK_UPDATEDON TIMESTAMP_NTZ(9)
);