create or replace TABLE ECC_HA_LINP (
	MANDT VARCHAR(3),
	LGNUM VARCHAR(3),
	IVNUM VARCHAR(10),
	IVPOS VARCHAR(4),
	ISTAT VARCHAR(1),
	DSTAT VARCHAR(1),
	LGPLA VARCHAR(10),
	IDATU VARCHAR(8),
	PLAUF VARCHAR(1),
	ANZLE NUMBER(38,3),
	ZZDATE VARCHAR(8),
	ZZTIME VARCHAR(6),
	SEQGEN NUMBER(38,0),
	FRMW_EXTRACTED_ON TIMESTAMP_NTZ(9),
	SNFLK_UPDATEDON TIMESTAMP_NTZ(9)
);