create or replace TABLE ECC_HA_ZMIMAC_POXREF (
	MANDT VARCHAR(3),
	EBELN1 VARCHAR(10),
	EBELP1 VARCHAR(5),
	EBELN2 VARCHAR(10),
	EBELP2 VARCHAR(5),
	LOEKZ VARCHAR(1),
	AEDAT VARCHAR(8),
	ERNAM VARCHAR(12),
	CHDAT VARCHAR(8),
	CHNAM VARCHAR(12),
	SEQGEN NUMBER(38,0),
	FRMW_EXTRACTED_ON TIMESTAMP_NTZ(9),
	SNFLK_UPDATEDON TIMESTAMP_NTZ(9)
);