create or replace TABLE ECC_HA_JEST (
	MANDT VARCHAR(3),
	OBJNR VARCHAR(22),
	STAT VARCHAR(5),
	INACT VARCHAR(1),
	CHGNR VARCHAR(3),
	ZZDATE VARCHAR(8),
	ZZTIME VARCHAR(6),
	SEQGEN NUMBER(38,0),
	FRMW_EXTRACTED_ON TIMESTAMP_NTZ(9),
	SNFLK_UPDATEDON TIMESTAMP_NTZ(9)
);