create or replace TABLE ECC_HA_T300T (
	MANDT VARCHAR(3),
	SPRAS VARCHAR(1),
	LGNUM VARCHAR(3),
	LNUMT VARCHAR(25),
	SEQGEN NUMBER(38,0),
	FRMW_EXTRACTED_ON TIMESTAMP_NTZ(9),
	SNFLK_UPDATEDON TIMESTAMP_NTZ(9)
);