create or replace TABLE ECC_HA_ZMM_GOF_MARA (
	KUNNR VARCHAR(10),
	VKORG VARCHAR(4),
	VTWEG VARCHAR(2),
	SPART VARCHAR(2),
	SAPMAT VARCHAR(18),
	GOFMAT VARCHAR(50),
	CREBY VARCHAR(12),
	CREDT VARCHAR(8),
	CHGBY VARCHAR(12),
	CHGDT VARCHAR(8),
	ZZDATE VARCHAR(8),
	ZZTIME VARCHAR(6),
	SEQGEN NUMBER(38,0),
	FRMW_EXTRACTED_ON TIMESTAMP_NTZ(9),
	SNFLK_UPDATEDON TIMESTAMP_NTZ(9)
);