create or replace TABLE ECC_HA_TJ02T (
	ISTAT VARCHAR(5),
	SPRAS VARCHAR(1),
	TXT04 VARCHAR(4),
	TXT30 VARCHAR(30),
	SEQGEN NUMBER(38,0),
	FRMW_EXTRACTED_ON TIMESTAMP_NTZ(9),
	SNFLK_UPDATEDON TIMESTAMP_NTZ(9)
);