create or replace TABLE ECC_HA_ZMM_GOF_ATTRIBUT (
	MANDT VARCHAR(3),
	OBJECTCLAS VARCHAR(15),
	OBJECTID VARCHAR(90),
	SAPMAT VARCHAR(18),
	FIELD_NAME VARCHAR(40),
	SEQUENCE VARCHAR(3),
	ATTRIBUTE_VALUE VARCHAR(255),
	CREBY VARCHAR(12),
	CREDT VARCHAR(8),
	CHGBY VARCHAR(12),
	CHGDT VARCHAR(8),
	ZZDATE VARCHAR(8),
	ZZTIME VARCHAR(6),
	SEQGEN NUMBER(38,0),
	FRMW_EXTRACTED_ON TIMESTAMP_NTZ(9),
	SNFLK_UPDATEDON TIMESTAMP_NTZ(9)
);