create or replace TABLE ECC_HA_ZMM_PU_GROUP (
	MANDT VARCHAR(3),
	EKGRP VARCHAR(3),
	EKNAM VARCHAR(18),
	AEDAT VARCHAR(8),
	ERNAM VARCHAR(12),
	CHDAT VARCHAR(8),
	CHNAM VARCHAR(12),
	FLAG VARCHAR(1),
	FRMW_EXTRACTED_ON TIMESTAMP_NTZ(9),
	SNFLK_UPDATEDON TIMESTAMP_NTZ(9)
);