create or replace TABLE ECC_HA_T301T (
	MANDT VARCHAR(3),
	SPRAS VARCHAR(1),
	LGNUM VARCHAR(3),
	LGTYP VARCHAR(3),
	LTYPT VARCHAR(25),
	SEQGEN NUMBER(38,0),
	FRMW_EXTRACTED_ON TIMESTAMP_NTZ(9),
	SNFLK_UPDATEDON TIMESTAMP_NTZ(9)
);