create or replace TABLE HCC_HA_T458A (
	MANDT VARCHAR(3),
	AUSSL VARCHAR(2),
	AUSKT VARCHAR(2),
	SELGP VARCHAR(1),
	ERDIS VARCHAR(1),
	ASPRI VARCHAR(2),
	ASNOT VARCHAR(1),
	FRMW_EXTRACTED_ON TIMESTAMP_NTZ(9),
	SNFLK_UPDATEDON TIMESTAMP_NTZ(9)
);