create or replace TABLE HCC_HA_MATN (
	CUOBJ VARCHAR(18),
	OBJEK VARCHAR(50),
	ATWRT VARCHAR(30),
	WERKS VARCHAR(4),
	ATINN VARCHAR(10),
	ATNAM VARCHAR(30),
	SEQGEN NUMBER(38,0),
	FRMW_EXTRACTED_ON TIMESTAMP_NTZ(9),
	SNFLK_UPDATEDON TIMESTAMP_NTZ(9)
);