create or replace TABLE HCC_HA_T059T (
	MANDT VARCHAR(3),
	SPRAS VARCHAR(1),
	MINDK VARCHAR(3),
	MTEXT VARCHAR(30),
	SEQGEN NUMBER(38,0),
	FRMW_EXTRACTED_ON TIMESTAMP_NTZ(9),
	SNFLK_UPDATEDON TIMESTAMP_NTZ(9)
);