create or replace TABLE HCC_HA_PLAF (
	PLNUM VARCHAR(10),
	PAART VARCHAR(4),
	PERTR VARCHAR(8),
	PSTMP NUMBER(38,0),
	PUSER VARCHAR(12),
	MEINS VARCHAR(3),
	SOBES VARCHAR(1),
	GSMNG NUMBER(38,3),
	PEDTR VARCHAR(8),
	PLWRK VARCHAR(4),
	PWWRK VARCHAR(4),
	MATNR VARCHAR(18),
	FLIEF VARCHAR(10),
	QUNUM VARCHAR(10),
	SEQGEN NUMBER(38,0),
	FRMW_EXTRACTED_ON TIMESTAMP_NTZ(9),
	SNFLK_UPDATEDON TIMESTAMP_NTZ(9)
);