create or replace TABLE HCC_HA_T024D (
	MANDT VARCHAR(3),
	WERKS VARCHAR(4),
	DISPO VARCHAR(3),
	DSNAM VARCHAR(18),
	DSTEL VARCHAR(12),
	EKGRP VARCHAR(3),
	MEMPF VARCHAR(12),
	GSBER VARCHAR(4),
	PRCTR VARCHAR(10),
	USRTYP VARCHAR(2),
	USRKEY VARCHAR(70),
	SEQGEN NUMBER(38,0),
	FRMW_EXTRACTED_ON TIMESTAMP_NTZ(9),
	SNFLK_UPDATEDON TIMESTAMP_NTZ(9)
);