create or replace TABLE IHS_ALTERNATES_PRE (
	PART_OBJ_ID NUMBER(38,0) NOT NULL,
	PART VARCHAR(100),
	FORMATTED_IHSMPN VARCHAR(100),
	FFF_CODE VARCHAR(100),
	FRMW_EXTRACTED_ON TIMESTAMP_NTZ(9),
	constraint PKEY_1 primary key (PART_OBJ_ID)
);