create or replace TABLE INFORECORDNOEXCHANGERATE (
	PLANTKEY NUMBER(38,0),
	MATERIALKEY NUMBER(38,0),
	SUPPLIERKEY NUMBER(38,0),
	MATERIALSOURCETYPEKEY NUMBER(38,0),
	PURCHASINGORGANIZATIONCODE VARCHAR(8),
	DATASOURCEKEY NUMBER(38,0),
	LATESTEXCHANGERATEKEY NUMBER(38,0)
);