create or replace TABLE INVENTORYBYMATERIAL (
	MATERIALKEY NUMBER(38,0),
	ONHANDQUANTITY NUMBER(30,6),
	ONHANDNONNETTABLEQUANTITY NUMBER(30,6),
	CONSIGNEDQUANTITY NUMBER(30,6),
	CONSIGNEDNONNETTABLEQUANTITY NUMBER(30,6)
);