create or replace TABLE JMD_HA_T001A (
	MANDT VARCHAR(3),
	BUKRS VARCHAR(4),
	CURTP VARCHAR(2),
	KURST VARCHAR(4),
	CURSR VARCHAR(1),
	CURDT VARCHAR(1),
	CURTP2 VARCHAR(2),
	KURST2 VARCHAR(4),
	CURSR2 VARCHAR(1),
	CURDT2 VARCHAR(1),
	FRMW_EXTRACTED_ON TIMESTAMP_NTZ(9),
	SNFLK_UPDATEDON TIMESTAMP_NTZ(9)
);