create or replace TABLE JMD_HA_ZMEDORG (
	MANDT VARCHAR(3),
	SAP_PLANT VARCHAR(4),
	PLANT_CODE VARCHAR(4),
	DIVISON VARCHAR(20),
	REGION VARCHAR(20),
	BUSINESS_AREA VARCHAR(4),
	COMPANY_CODE VARCHAR(4),
	FRMW_EXTRACTED_ON TIMESTAMP_NTZ(9),
	SNFLK_UPDATEDON TIMESTAMP_NTZ(9)
);