create or replace TABLE JMD_HA_EQUK (
	MANDT VARCHAR(3),
	MATNR VARCHAR(18),
	WERKS VARCHAR(4),
	BDATU VARCHAR(8),
	VDATU VARCHAR(8),
	QUNUM VARCHAR(10),
	ERDAT VARCHAR(8),
	ERNAM VARCHAR(12),
	SCMNG NUMBER(38,3),
	FRMW_EXTRACTED_ON TIMESTAMP_NTZ(9),
	SNFLK_UPDATEDON TIMESTAMP_NTZ(9)
);