create or replace TABLE JMD_HA_T320 (
	MANDT VARCHAR(3),
	WERKS VARCHAR(4),
	LGORT VARCHAR(4),
	LGNUM VARCHAR(3),
	OBEST VARCHAR(1),
	LGNTB VARCHAR(1),
	SLGOR VARCHAR(1),
	OBTYP VARCHAR(3),
	LGREF VARCHAR(2),
	CENSY VARCHAR(1),
	FRMW_EXTRACTED_ON TIMESTAMP_NTZ(9),
	SNFLK_UPDATEDON TIMESTAMP_NTZ(9)
);