create or replace TABLE JMD_HA_T005T (
	MANDT VARCHAR(3),
	SPRAS VARCHAR(1),
	LAND1 VARCHAR(3),
	LANDX VARCHAR(15),
	NATIO VARCHAR(15),
	LANDX50 VARCHAR(50),
	NATIO50 VARCHAR(50),
	PRQ_SPREGT VARCHAR(30),
	FRMW_EXTRACTED_ON TIMESTAMP_NTZ(9),
	SNFLK_UPDATEDON TIMESTAMP_NTZ(9)
);