create or replace TABLE JMD_HA_AMPL (
	MANDT VARCHAR(3),
	BMATN VARCHAR(18),
	AMPNR VARCHAR(5),
	EMATN VARCHAR(18),
	MFRNR VARCHAR(10),
	WERKS VARCHAR(4),
	DATUV VARCHAR(8),
	DATUB VARCHAR(8),
	REVLV VARCHAR(2),
	AMPSP VARCHAR(4),
	REOAM VARCHAR(1),
	ERDAT VARCHAR(8),
	ERNAM VARCHAR(12),
	FRMW_EXTRACTED_ON TIMESTAMP_NTZ(9),
	SNFLK_UPDATEDON TIMESTAMP_NTZ(9)
);