create or replace TABLE JPS_HA_T023 (
	MANDT VARCHAR(3),
	MATKL VARCHAR(9),
	SPART VARCHAR(2),
	LREF3 VARCHAR(3),
	WWGDA VARCHAR(40),
	WWGPA VARCHAR(40),
	ABTNR VARCHAR(4),
	BEGRU VARCHAR(4),
	GEWEI VARCHAR(3),
	J_1BNBM VARCHAR(16),
	BKLAS VARCHAR(4),
	EKWSL VARCHAR(4),
	ANLKL VARCHAR(8),
	DEF_SCHDSC VARCHAR(6),
	PRICE_GROUP VARCHAR(6),
	FRMW_EXTRACTED_ON TIMESTAMP_NTZ(9),
	SNFLK_UPDATEDON TIMESTAMP_NTZ(9)
);