create or replace TABLE MOVEMENTSNOEXCHANGERATE (
	MOVEMENTYEAR NUMBER(38,0),
	MOVEMENTDOCUMENTNUMBER VARCHAR(40),
	MOVEMENTDOCUMENTITEM NUMBER(38,0),
	DATASOURCEKEY NUMBER(38,0),
	CURRENCYCODE VARCHAR(5),
	LATESTEXCHANGERATEKEY NUMBER(38,0)
);