create or replace TABLE PLA_HA_T006A (
	MANDT VARCHAR(3),
	SPRAS VARCHAR(1),
	MSEHI VARCHAR(3),
	MSEH3 VARCHAR(3),
	MSEH6 VARCHAR(6),
	MSEHT VARCHAR(10),
	MSEHL VARCHAR(30),
	FRMW_EXTRACTED_ON TIMESTAMP_NTZ(9),
	SNFLK_UPDATEDON TIMESTAMP_NTZ(9)
);