create or replace TABLE PLA_HA_A017 (
	MANDT VARCHAR(3),
	KAPPL VARCHAR(2),
	KSCHL VARCHAR(4),
	LIFNR VARCHAR(10),
	MATNR VARCHAR(18),
	EKORG VARCHAR(4),
	WERKS VARCHAR(4),
	ESOKZ VARCHAR(1),
	DATBI VARCHAR(8),
	DATAB VARCHAR(8),
	KNUMH VARCHAR(10),
	FRMW_EXTRACTED_ON TIMESTAMP_NTZ(9),
	SNFLK_UPDATEDON TIMESTAMP_NTZ(9)
);