create or replace TABLE PLA_HA_T023T (
	MANDT VARCHAR(3),
	SPRAS VARCHAR(1),
	MATKL VARCHAR(9),
	WGBEZ VARCHAR(20),
	WGBEZ60 VARCHAR(60),
	FRMW_EXTRACTED_ON TIMESTAMP_NTZ(9),
	SNFLK_UPDATEDON TIMESTAMP_NTZ(9)
);