create or replace TABLE SCMDB_STORAGETYPESTD (
	STORAGETYPESTDID NUMBER(38,0),
	STORAGETYPESTDCODE VARCHAR(10),
	DESCRIPTION VARCHAR(50),
	UPDATEUSER VARCHAR(25),
	UPDATEDTS TIMESTAMP_NTZ(9),
	FRMW_EXTRACTED_ON TIMESTAMP_NTZ(9),
	SNFLK_UPDATEDON TIMESTAMP_NTZ(9)
);