create or replace TABLE SCMDB_MFRPARTCLASSMAP (
	MFRPARTID NUMBER(38,0),
	CLASSMAPID NUMBER(38,0),
	CLASSMAPVALUEID NUMBER(38,0),
	VALUENUMERIC NUMBER(38,3),
	UOMID NUMBER(38,0),
	FRMW_EXTRACTED_ON TIMESTAMP_NTZ(9),
	SNFLK_UPDATEDON TIMESTAMP_NTZ(9)
);