create or replace TABLE SCMDB_MRPRECOMMENDATIONSTD (
	MRPRECOMMENDATIONSTDID NUMBER(38,0),
	MRPRECOMMENDATIONSTDCODE VARCHAR(50),
	MRPRECOMMENDATIONGROUP VARCHAR(25),
	FRMW_EXTRACTED_ON TIMESTAMP_NTZ(9),
	SNFLK_UPDATEDON TIMESTAMP_NTZ(9)
);