create or replace TABLE SCMDB_CORPORATION (
	CORPORATIONID NUMBER(38,0),
	CORPORATIONNAME VARCHAR(65),
	CREATEDTS TIMESTAMP_NTZ(9),
	UPDATEDTS TIMESTAMP_NTZ(9),
	WEBSITEURL VARCHAR(120),
	TWITTER VARCHAR(35),
	TICKERSYMBOL VARCHAR(20),
	FACEBOOKPAGE VARCHAR(120),
	MARKET VARCHAR(35),
	SALESFORCEID VARCHAR(20),
	YOUTUBEURL VARCHAR(120),
	CORPORATIONLEGALNAME VARCHAR(200),
	FRMW_EXTRACTED_ON TIMESTAMP_NTZ(9),
	SNFLK_UPDATEDON TIMESTAMP_NTZ(9)
);