create or replace TABLE SCMDB_PURCHASEDOCUMENTCATEGORY (
	DATASOURCEID NUMBER(38,0),
	PURCHASEDOCUMENTCATEGORYCODE VARCHAR(4),
	PURCHASEDOCUMENTCATEGORYSTDID NUMBER(38,0),
	DESCRIPTION VARCHAR(50),
	IMPORTJOBID NUMBER(38,0),
	CREATEUSER VARCHAR(25),
	CREATEDTS TIMESTAMP_NTZ(9),
	UPDATEUSER VARCHAR(25),
	UPDATEDTS TIMESTAMP_NTZ(9),
	FRMW_EXTRACTED_ON TIMESTAMP_NTZ(9),
	SNFLK_UPDATEDON TIMESTAMP_NTZ(9)
);