create or replace TABLE SCMDB_BUYERCODE (
	DATASOURCEID NUMBER(38,0),
	BUYERCODE VARCHAR(10),
	CONTACTID NUMBER(38,0),
	IMPORTJOBID NUMBER(38,0),
	CREATEUSER VARCHAR(10),
	CREATEDTS TIMESTAMP_NTZ(9),
	UPDATEUSER VARCHAR(10),
	UPDATEDTS TIMESTAMP_NTZ(9),
	FRMW_EXTRACTED_ON TIMESTAMP_NTZ(9),
	SNFLK_UPDATEDON TIMESTAMP_NTZ(9)
);