create or replace TABLE SCMDB_SITEPARTTYPESTD (
	SITEPARTTYPESTDID NUMBER(38,0),
	SITEPARTTYPESTDCODE VARCHAR(30),
	MATERIALCODEASSIGNEDCLASSID NUMBER(38,0),
	MATERIALCODEPRECEDENCE NUMBER(38,0),
	FRMW_EXTRACTED_ON TIMESTAMP_NTZ(9),
	SNFLK_UPDATEDON TIMESTAMP_NTZ(9)
);