create or replace TABLE SCMDB_SITEPARTSOURCECATEGORYSTD (
	SITEPARTSOURCECATEGORYSTDID NUMBER(38,0),
	DESCRIPTION VARCHAR(30),
	DELETEFLAG BOOLEAN,
	CREATEUSER VARCHAR(25),
	CREATEDTS TIMESTAMP_NTZ(9),
	UPDATEUSER VARCHAR(25),
	UPDATEDTS TIMESTAMP_NTZ(9),
	FRMW_EXTRACTED_ON TIMESTAMP_NTZ(9),
	SNFLK_UPDATEDON TIMESTAMP_NTZ(9)
);