create or replace TABLE SCMDB_MOVEMENTTYPE (
	MOVEMENTTYPEID NUMBER(38,0),
	DATASOURCEID NUMBER(38,0),
	MOVEMENTTYPECODE VARCHAR(10),
	DESCRIPTION VARCHAR(50),
	MOVEMENTTYPESTDID NUMBER(38,0),
	DELETEFLAG BOOLEAN,
	IMPORTJOBID NUMBER(38,0),
	CREATEUSER VARCHAR(25),
	CREATEDTS TIMESTAMP_NTZ(9),
	UPDATEUSER VARCHAR(25),
	UPDATEDTS TIMESTAMP_NTZ(9),
	DEBITCREDITINDICATOR VARCHAR(1),
	FRMW_EXTRACTED_ON TIMESTAMP_NTZ(9),
	SNFLK_UPDATEDON TIMESTAMP_NTZ(9)
);