create or replace TABLE SCMDB_SALESDOCUMENTTYPE (
	DATASOURCEID NUMBER(38,0),
	SALESDOCUMENTTYPECODE VARCHAR(4),
	SALESDOCUMENTTYPESTDID NUMBER(38,0),
	DESCRIPTION VARCHAR(50),
	IMPORTJOBID NUMBER(38,0),
	DELETEFLAG BOOLEAN,
	CREATEUSER VARCHAR(25),
	CREATEDTS TIMESTAMP_NTZ(9),
	UPDATEUSER VARCHAR(25),
	UPDATEDTS TIMESTAMP_NTZ(9),
	FRMW_EXTRACTED_ON TIMESTAMP_NTZ(9),
	SNFLK_UPDATEDON TIMESTAMP_NTZ(9)
);