create or replace TABLE SCMDB_DEMANDTYPESTD (
	DEMANDTYPESTDID NUMBER(38,0),
	DEMANDTYPESTDCODE VARCHAR(65),
	ISMASTERSCHEDULE BOOLEAN,
	FRMW_EXTRACTED_ON TIMESTAMP_NTZ(9),
	SNFLK_UPDATEDON TIMESTAMP_NTZ(9)
);