create or replace TABLE SCMDB_INVENTORYTYPE (
	INVENTORYTYPEID NUMBER(38,0),
	DATASOURCEID NUMBER(38,0),
	INVENTORYTYPECODE VARCHAR(20),
	DESCRIPTION VARCHAR(50),
	PROCESSINGRULE VARCHAR(50),
	INVENTORYTYPESTDID NUMBER(38,0),
	IMPORTJOBID NUMBER(38,0),
	DELETEFLAG BOOLEAN,
	CREATEUSER VARCHAR(25),
	CREATEDTS TIMESTAMP_NTZ(9),
	UPDATEUSER VARCHAR(25),
	UPDATEDTS TIMESTAMP_NTZ(9),
	FRMW_EXTRACTED_ON TIMESTAMP_NTZ(9),
	SNFLK_UPDATEDON TIMESTAMP_NTZ(9)
);