create or replace TABLE SCMDB_COMMODITYWEBSITE (
	COMMODITYWEBSITEID NUMBER(38,0),
	CLASSID NUMBER(38,0),
	WEBSITENAME VARCHAR(35),
	LINK VARCHAR(1000),
	SEARCHFLAG VARCHAR(5),
	COMMENT VARCHAR(35),
	ISACTIVE NUMBER(38,0),
	FRMW_EXTRACTED_ON TIMESTAMP_NTZ(9),
	SNFLK_UPDATEDON TIMESTAMP_NTZ(9)
);