create or replace TABLE SCMDB_PURCHASEHISTORYTYPESTD (
	PURCHASEHISTORYTYPESTDID NUMBER(38,0),
	PURCHASEHISTORYTYPESTDCODE VARCHAR(50),
	FRMW_EXTRACTED_ON TIMESTAMP_NTZ(9),
	SNFLK_UPDATEDON TIMESTAMP_NTZ(9)
);