create or replace TABLE SCMDB_INVENTORYLOCATIONTYPE (
	LOCATIONTYPEID NUMBER(38,0),
	DATASOURCEID NUMBER(38,0),
	LOCATIONTYPECODE VARCHAR(50),
	DESCRIPTION VARCHAR(50),
	LOCATIONTYPESTDID NUMBER(38,0),
	IMPORTJOBID NUMBER(38,0),
	CREATEUSER VARCHAR(25),
	CREATEDTS TIMESTAMP_NTZ(9),
	UPDATEUSER VARCHAR(25),
	UPDATEDTS TIMESTAMP_NTZ(9),
	FRMW_EXTRACTED_ON TIMESTAMP_NTZ(9),
	SNFLK_UPDATEDON TIMESTAMP_NTZ(9)
);