create or replace TABLE SCMDB_INVENTORYLOCATIONTYPEMAP (
	DATASOURCEID NUMBER(38,0),
	LIKESEARCHSTRING VARCHAR(250),
	NOTLIKESEARCHSTRING VARCHAR(250),
	LOCATIONTYPECODE VARCHAR(50),
	FRMW_EXTRACTED_ON TIMESTAMP_NTZ(9),
	SNFLK_UPDATEDON TIMESTAMP_NTZ(9)
);