create or replace TABLE SCMDB_SALESDOCUMENTTYPESTD (
	SALESDOCUMENTTYPESTDID NUMBER(38,0),
	SALESDOCUMENTTYPESTDCODE VARCHAR(65),
	FRMW_EXTRACTED_ON TIMESTAMP_NTZ(9),
	SNFLK_UPDATEDON TIMESTAMP_NTZ(9)
);