create or replace TABLE SCMDB_ORGANIZATION (
	DATASOURCEID NUMBER(38,0),
	ORGANIZATIONCODE VARCHAR(4),
	ORGANIZATIONTYPEID NUMBER(38,0),
	ORGANIZATIONNAME VARCHAR(65),
	DELETEFLAG BOOLEAN,
	IMPORTJOBID NUMBER(38,0),
	CREATEUSER VARCHAR(25),
	CREATEDTS TIMESTAMP_NTZ(9),
	UPDATEUSER VARCHAR(25),
	UPDATEDTS TIMESTAMP_NTZ(9),
	FRMW_EXTRACTED_ON TIMESTAMP_NTZ(9),
	SNFLK_UPDATEDON TIMESTAMP_NTZ(9)
);