create or replace TABLE SCMDB_CORPORATIONDSTOMARKETSECTOR (
	CORPORATIONDSID NUMBER(38,0),
	MARKETSECTORID NUMBER(38,0),
	SITEID NUMBER(38,0),
	FRMW_EXTRACTED_ON TIMESTAMP_NTZ(9),
	SNFLK_UPDATEDON TIMESTAMP_NTZ(9)
);