create or replace TABLE SCMDB_SITETYPE (
	SITETYPEID NUMBER(38,0),
	SITETYPECODE VARCHAR(65),
	SITETYPECODEWEBPLAN VARCHAR(65),
	DEFINITION VARCHAR(400),
	FRMW_EXTRACTED_ON TIMESTAMP_NTZ(9),
	SNFLK_UPDATEDON TIMESTAMP_NTZ(9)
);