create or replace TABLE SCMDB_PURCHASESCHEDULETYPESTD (
	PURCHASESCHEDULETYPESTDID NUMBER(38,0),
	PURCHASESCHEDULETYPESTDCODE VARCHAR(20),
	FRMW_EXTRACTED_ON TIMESTAMP_NTZ(9),
	SNFLK_UPDATEDON TIMESTAMP_NTZ(9)
);