create or replace TABLE SCMDB_CORPORATIONDSTYPESTD (
	CORPORATIONDSTYPESTDID NUMBER(38,0),
	CORPORATIONDSTYPESTDCODE VARCHAR(65),
	CORPORATIONDSTYPESTDCODESHORT VARCHAR(5),
	ASSIGNABLE BOOLEAN,
	FRMW_EXTRACTED_ON TIMESTAMP_NTZ(9),
	SNFLK_UPDATEDON TIMESTAMP_NTZ(9)
);