create or replace TABLE SCMDB_CURRENCYSTD (
	CURRENCYSTDID NUMBER(38,0),
	CURRENCYSTDCODE VARCHAR(3),
	CURRENCYSTDNAME VARCHAR(20),
	EXCHANGERATE NUMBER(38,30),
	UPDATEUSER VARCHAR(25),
	UPDATEDTS TIMESTAMP_NTZ(9),
	FRMW_EXTRACTED_ON TIMESTAMP_NTZ(9),
	SNFLK_UPDATEDON TIMESTAMP_NTZ(9)
);