create or replace TABLE SCMDB_UOM (
	UOMID NUMBER(38,0),
	UOM VARCHAR(25),
	UOMDESC VARCHAR(45),
	UOMBASE NUMBER(38,0),
	CONVERSIONVALUE FLOAT,
	OPERATOR VARCHAR(1),
	FRMW_EXTRACTED_ON TIMESTAMP_NTZ(9),
	SNFLK_UPDATEDON TIMESTAMP_NTZ(9)
);