create or replace TABLE SCMDB_COMMENT (
	COMMENTID NUMBER(38,0),
	COMMENT VARCHAR(255),
	USERID NUMBER(38,0),
	COMMENTDATE TIMESTAMP_NTZ(9),
	FRMW_EXTRACTED_ON TIMESTAMP_NTZ(9),
	SNFLK_UPDATEDON TIMESTAMP_NTZ(9)
);