create or replace TABLE SCMDB_SOURCINGOWNERTYPESTD (
	SOURCINGOWNERTYPESTDID NUMBER(38,0),
	SOURCINGOWNERTYPESTDCODE VARCHAR(20),
	FRMW_EXTRACTED_ON TIMESTAMP_NTZ(9),
	SNFLK_UPDATEDON TIMESTAMP_NTZ(9)
);