create or replace TABLE SCMDB_CORPORATIONMAINTENANCEVALUE (
	CORPORATIONMAINTENANCEVALUEID NUMBER(38,0),
	CORPORATIONMAINTENANCEID NUMBER(38,0),
	CORPORATIONMAINTENANCEVALUENAME VARCHAR(65),
	SEQ NUMBER(38,0),
	FRMW_EXTRACTED_ON TIMESTAMP_NTZ(9),
	SNFLK_UPDATEDON TIMESTAMP_NTZ(9)
);