create or replace TABLE SCMDB_SPECIALSTOCKS (
	DATASOURCEID NUMBER(38,0),
	SPECIALSTOCKSCODE VARCHAR(1),
	DESCRIPTION VARCHAR(50),
	IMPORTJOBID NUMBER(38,0),
	DELETEFLAG BOOLEAN,
	CREATEUSER VARCHAR(25),
	CREATEDTS TIMESTAMP_NTZ(9),
	UPDATEUSER VARCHAR(25),
	UPDATEDTS TIMESTAMP_NTZ(9),
	SPECIALSTOCKSSTDID NUMBER(38,0),
	FRMW_EXTRACTED_ON TIMESTAMP_NTZ(9),
	SNFLK_UPDATEDON TIMESTAMP_NTZ(9)
);