create or replace TABLE SCMDB_SALESITEMTYPE (
	DATASOURCEID NUMBER(38,0),
	SALESITEMTYPECODE VARCHAR(4),
	SALESITEMTYPESTDID NUMBER(38,0),
	DESCRIPTION VARCHAR(50),
	IMPORTJOBID NUMBER(38,0),
	CREATEUSER VARCHAR(25),
	CREATEDTS TIMESTAMP_NTZ(9),
	UPDATEUSER VARCHAR(25),
	UPDATEDTS TIMESTAMP_NTZ(9),
	FRMW_EXTRACTED_ON TIMESTAMP_NTZ(9),
	SNFLK_UPDATEDON TIMESTAMP_NTZ(9)
);