create or replace TABLE SCMDB_CLASSIFICATIONSTATUS (
	CLASSIFICATIONSTATUSID NUMBER(38,0),
	CLASSIFICATIONSTATUSCODE VARCHAR(65),
	CONFLICTPRECEDENCE NUMBER(38,0),
	FRMW_EXTRACTED_ON TIMESTAMP_NTZ(9),
	SNFLK_UPDATEDON TIMESTAMP_NTZ(9)
);