create or replace TABLE SCMDB_PAYMENTTERMSTYPESTD (
	PAYMENTTERMSTYPESTDID NUMBER(38,0),
	PAYMENTTERMSTYPESTDCODE VARCHAR(65),
	NOOFDAYS NUMBER(38,0),
	FRMW_EXTRACTED_ON TIMESTAMP_NTZ(9),
	SNFLK_UPDATEDON TIMESTAMP_NTZ(9)
);