create or replace TABLE SCMDB_CORPORATIONMAINTENANCE (
	CORPORATIONMAINTENANCEID NUMBER(38,0),
	CORPORATIONMAINTENANCENAME VARCHAR(65),
	MAINTENANCELEVEL VARCHAR(30),
	CORPORATIONDSTYPESTDID NUMBER(38,0),
	FRMW_EXTRACTED_ON TIMESTAMP_NTZ(9),
	SNFLK_UPDATEDON TIMESTAMP_NTZ(9)
);