create or replace TABLE SCMDB_CDM_INTERNALSTATUS (
	INTERNALSTATUSID NUMBER(38,0),
	INTERNALSTATUS VARCHAR(50),
	CREATEDTS TIMESTAMP_NTZ(9),
	CREATEUSER NUMBER(38,0),
	UPDATEUSER NUMBER(38,0),
	UPDATEDTS TIMESTAMP_NTZ(9),
	FRMW_EXTRACTED_ON TIMESTAMP_NTZ(9),
	SNFLK_UPDATEDON TIMESTAMP_NTZ(9)
);