create or replace TABLE SCMDB_INVENTORYLOCATION (
	SITEID NUMBER(38,0),
	LOCATION VARCHAR(10),
	LOCATIONNAME VARCHAR(20),
	LOCATIONTYPEID NUMBER(38,0),
	MRPINDICATOR NUMBER(38,0),
	DELETEFLAG BOOLEAN,
	IMPORTJOBID NUMBER(38,0),
	CREATEUSER VARCHAR(30),
	CREATEDTS TIMESTAMP_NTZ(9),
	UPDATEUSER VARCHAR(30),
	UPDATEDTS TIMESTAMP_NTZ(9),
	FRMW_EXTRACTED_ON TIMESTAMP_NTZ(9),
	SNFLK_UPDATEDON TIMESTAMP_NTZ(9)
);