create or replace TABLE SCMDB_SC_USERS (
	USER_ID NUMBER(38,0),
	USER_CD VARCHAR(25),
	USER_PASSWORD VARCHAR(14),
	USER_LAST_NM VARCHAR(50),
	USER_FIRST_NM VARCHAR(50),
	ACTIVE_FLG VARCHAR(1),
	EMAIL_ADDR VARCHAR(40),
	ADOBJECTGUID VARCHAR(16777216),
	FRMW_EXTRACTED_ON TIMESTAMP_NTZ(9),
	SNFLK_UPDATEDON TIMESTAMP_NTZ(9)
);