create or replace TABLE SCMDB_SAT_SCM_SITESUPPLIER (
	CORPORATIONID NUMBER(38,0),
	SITEID NUMBER(38,0),
	SAT_SUPPLYCHAINID NUMBER(38,0),
	PURCHASESTRATEGY BOOLEAN,
	CREATEUSER VARCHAR(20),
	CREATEDTS TIMESTAMP_NTZ(9),
	UPDATEUSER VARCHAR(20),
	UPDATEDTS TIMESTAMP_NTZ(9),
	FRMW_EXTRACTED_ON TIMESTAMP_NTZ(9),
	SNFLK_UPDATEDON TIMESTAMP_NTZ(9)
);