create or replace TABLE SCMDB_PURCHASEITEMCATEGORYSTD (
	PURCHASEITEMCATEGORYSTDID NUMBER(38,0),
	PURCHASEITEMCATEGORYSTDCODE VARCHAR(20),
	FRMW_EXTRACTED_ON TIMESTAMP_NTZ(9),
	SNFLK_UPDATEDON TIMESTAMP_NTZ(9)
);