create or replace TABLE SCMDB_CORPORATIONINFO (
	CORPORATIONID NUMBER(38,0),
	CORPORATIONMAINTENANCEID NUMBER(38,0),
	CORPORATIONMAINTENANCEVALUEID NUMBER(38,0),
	CLASSID NUMBER(38,0),
	MARKETSECTORID NUMBER(38,0),
	CHARACTERID NUMBER(38,0),
	CLASSMAPVALUEID NUMBER(38,0),
	CHARACTERID2 NUMBER(38,0),
	CLASSMAPVALUEID2 NUMBER(38,0),
	FRMW_EXTRACTED_ON TIMESTAMP_NTZ(9),
	SNFLK_UPDATEDON TIMESTAMP_NTZ(9)
);