create or replace TABLE SCMDB_PURCHASEDOCUMENTCATEGORYSTD (
	PURCHASEDOCUMENTCATEGORYSTDID NUMBER(38,0),
	PURCHASEDOCUMENTCATEGORYSTDCODE VARCHAR(20),
	FRMW_EXTRACTED_ON TIMESTAMP_NTZ(9),
	SNFLK_UPDATEDON TIMESTAMP_NTZ(9)
);