create or replace TABLE TEMPAMLS (
	AMLKEY NUMBER(38,0),
	MANUFACTURERPARTKEY NUMBER(38,0),
	AMLREFERENCE VARCHAR(256),
	PLANTKEY NUMBER(38,0),
	MANUFACTURERPARTCODE VARCHAR(16777216),
	MANUFACTURERKEY NUMBER(38,0),
	MANUFACTURERCODE VARCHAR(60),
	GLOBALMANUFACTURERNAME VARCHAR(130)
);