create or replace TABLE TMP_V_ECC_HA_MRPHEADER (
	SITEPARTCODE VARCHAR(18),
	BASEUNITOFMEASUREDSCODE VARCHAR(3),
	SITECODE VARCHAR(4),
	MRPSCENARIO VARCHAR(3),
	MRPPROCESSEDFLAG VARCHAR(1),
	MRPNUMBER VARCHAR(10),
	LOWLEVELCODE VARCHAR(3),
	MRPCURRENTASOFDTS VARCHAR(15),
	UPDATED_ON TIMESTAMP_LTZ(9),
	MDKP_SNAPSHOTDATE DATE
);