create or replace TABLE SFIX (
	PURCHASEDOCUMENTNUMBER VARCHAR(12),
	PURCHASEDOCUMENTITEM NUMBER(38,0),
	MATERIALDOCUMENTNUMBER VARCHAR(40),
	MATERIALDOCUMENTITEM NUMBER(38,0),
	MATERIALDOCUMENTYEAR NUMBER(38,0),
	DATASOURCEKEY NUMBER(38,0),
	CURRENTSUPPLIER NUMBER(38,0),
	NEWSUPPLIERKEY NUMBER(38,0),
	SUPPLIERCODE VARCHAR(60)
);