create or replace TABLE ELT_HISTORY (
	ELT_HISTORYKEY NUMBER(38,0) NOT NULL autoincrement,
	PROCEDURENAME VARCHAR(100) NOT NULL COLLATE 'en-ci',
	STARTDATE TIMESTAMP_NTZ(9) NOT NULL,
	ENDDATE TIMESTAMP_NTZ(9),
	ROWSINSERTED NUMBER(38,0),
	ROWSUPDATED NUMBER(38,0),
	primary key (ELT_HISTORYKEY)
);