create or replace TABLE PIPE_USAGE_HISTORY (
	PIPE_ID NUMBER(38,0),
	PIPE_NAME VARCHAR(16777216),
	START_TIME TIMESTAMP_LTZ(0),
	END_TIME TIMESTAMP_LTZ(9),
	CREDITS_USED NUMBER(38,9),
	BYTES_INSERTED FLOAT,
	FILES_INSERTED VARIANT
);