create or replace TABLE WAREHOUSE_METERING_HISTORY (
	START_TIME TIMESTAMP_LTZ(0),
	END_TIME TIMESTAMP_LTZ(0),
	WAREHOUSE_ID NUMBER(38,0),
	WAREHOUSE_NAME VARCHAR(16777216),
	CREDITS_USED NUMBER(38,9),
	CREDITS_USED_COMPUTE NUMBER(38,9),
	CREDITS_USED_CLOUD_SERVICES NUMBER(38,9)
);