create or replace task TASK_DIMIHSBASIC
	warehouse=WH_TASKS
	schedule='USING CRON 0 21 * * * America/New_York'
	USER_TASK_TIMEOUT_MS=43200000
	when SYSTEM$STREAM_HAS_DATA('CONFORMED.STM_IHS_BASIC')
	as CALL CONFORMED.DIMIHSBASIC_ADD();