create or replace task TASK_DIMIHSALTERNATES
	warehouse=WH_TASKS
	USER_TASK_TIMEOUT_MS=43200000
	after PRD.CONFORMED.TASK_DIMIHSLIFECYCLE
	when SYSTEM$STREAM_HAS_DATA('CONFORMED.STM_IHS_ALTERNATES')
	as CALL CONFORMED.DIMIHSALTERNATES_ADD();