create or replace task TASK_FACTSFPROJECTREQUESTS
	warehouse=WH_TASKS
	after PRD.CONFORMED.TASK_START_FACTSFPROJECTREQUESTS
	when SYSTEM$STREAM_HAS_DATA('CONFORMED.STM_SF_PROJECTREQUESTS')
	as CALL CONFORMED.FACTSFPROJECTREQUESTS_ADD();